---
- hosts: all
  roles:

    - role: openmicroscopy.postgresql
      postgresql_users_databases:
      - user: alice
        password: alice123
        databases: [alice]

    - role: ansible-role-prometheus-postgres
      prometheus_postgres_dbname: alice
      prometheus_postgres_port: 19187
      prometheus_postgres_query_filenames:
      - queries-default.yml
      - queries-pg_statio_user_tables.yml
