---
# tasks file for prometheus-postgres

- name: prometheus postgres | create directories
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
  - /opt/prometheus/postgres
  - /etc/prometheus

- name: prometheus postgres | download
  become: yes
  get_url:
    url: https://github.com/wrouesnel/postgres_exporter/releases/download/v{{ prometheus_postgres_version }}/postgres_exporter_v{{ prometheus_postgres_version }}_linux-amd64.tar.gz
      #https://github.com/wrouesnel/postgres_exporter/releases/download/v{{ prometheus_postgres_version }}/postgres_exporter
    checksum: sha256:{{ prometheus_postgres_sha256 }}
    dest: /opt/prometheus/postgres_exporter_v{{ prometheus_postgres_version }}_linux-amd64.tar.gz
    #dest: /opt/prometheus/postgres/postgres_exporter-0.2.2

- name: prometheus postgres | install postgres-exporter
  become: yes
  unarchive:
    src: /opt/prometheus/postgres_exporter_v{{ prometheus_postgres_version }}_linux-amd64.tar.gz
    dest: /opt/prometheus
    group: root
    owner: root
    remote_src: yes

- name: prometheus postgres | symlink postgres-exporter
  become: yes
  file:
    src: /opt/prometheus/postgres_exporter_v{{ prometheus_postgres_version }}_linux-amd64
    path: /opt/prometheus/postgres_exporter
    force: yes
    state: link
  notify:
  - restart prometheus-postgres

- name: prometheus postgres | configuration file
  become: yes
  assemble:
    dest: /etc/prometheus/postgres-queries.yml
    regexp: "^{{ prometheus_postgres_query_filenames | join('|') }}$"
    remote_src: false
    src: files/
  notify:
  - restart prometheus-postgres

- name: prometheus postgres | server systemd service
  become: yes
  template:
    dest: /etc/systemd/system/prometheus-postgres-exporter.service
    src: systemd-system-prometheus-postgres-exporter-service.j2
  notify:
  - restart prometheus-postgres

- name: prometheus postgres | enable and start server systemd
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: prometheus-postgres-exporter.service
    state: started
